### ISSUE TITLE
Enable dependabot alerts

### ISSUE THREAD

**Issue by mscho527** [cariluo/cariluo.github.io#1]
Could you enable dependabot alerts from https://github.com/cariluo/cariluo.github.io/security ?

**Comment by ShaunWeatherly** [comment]
Would it be easier to migrate this to the organization account first? Or do we plan to make all our edits here and then only migrate when all is ready?

Github allows only one page per account, so either way I think we should migrate in case Carina ever wants to host her own website here!

**Comment by cariluo** [comment]
Dependabot alerts have been enabled.
