### ISSUE TITLE
Would it be easier to migrate this to the organization account first? Or do we plan to make all our edits here and then only migrate when all is ready?

### ISSUE THREAD

**Issue by mscho527** [cariluo/cariluo.github.io#2]
Would it be easier to migrate this to the organization account first? Or do we plan to make all our edits here and then only migrate when all is ready?

Github allows only one page per account, so either way I think we should migrate in case Carina ever wants to host her own website here!

_Originally posted by @ShaunWeatherly in https://github.com/cariluo/cariluo.github.io/issues/1#issuecomment-2541474493_

**Comment by mscho527** [comment]
This seems to be a separate issue, so I created a new one. I think we want to migrate when it is close to ready.

**Comment by cariluo** [comment]
I don’t plan to create a personal website within the next year, so I’m fine keeping it here until it’s ready.
